CREATE TABLE application_schemas (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  opportunity_id INTEGER NOT NULL
    REFERENCES opportunities (id) ON DELETE CASCADE,
  version SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT unique_opportunity_id_version UNIQUE (opportunity_id, version)
);

COMMENT ON TABLE application_schemas IS
  'A set of canonical fields for one opportunity.';
