create table application_schemas (
  id bigint primary key generated always as identity,
  created_at timestamp with time zone not null default now(),
  opportunity_id bigint not null
    references opportunities (id) on delete cascade,
  version smallint not null generated by default as identity,
  constraint unique_opportunity_id_version unique (opportunity_id, version)
);

comment on table application_schemas is
  'A set of canonical fields for one opportunity.'
