INSERT INTO canonical_fields (id, label, short_code, data_type) OVERRIDING SYSTEM VALUE VALUES
(1, 'Organization Name', 'organization_name', '{ type: "string" }' ),
(2, 'Organization Legal Name' , 'organization_legal_name', '{ type: "string" }' ),
(3, 'Organization DBA Name' , 'organization_dba_name', '{ type: "string" }' ),
(4, 'Organization Acronym' , 'organization_acronym', '{ type: "string" }' ),
(5, 'Organization ID' , 'organization_id', '{ type: "string" }' ),
(6, 'Organization Charitable Organization' , 'organization_charitable_organization', '{ type: "string" }' ),
(7, 'Organization Entity Type' , 'organization_entity_type', '{ type: "string" }' ),
(8, 'Organization Tax ID' , 'organization_tax_id', '{ type: "string" }' ),
(9, 'Organization Street Address 1' , 'organization_street_address_1', '{ type: "string" }' ),
(10, 'Organization Street Address 2' , 'organization_street_address_2', '{ type: "string" }' ),
(11, 'Organization City' , 'organization_city', '{ type: "string" }' ),
(12, 'Organization County' , 'organization_county', '{ type: "string" }' ),
(13, 'Organization State/Province' , 'organization_state_province', '{ type: "string" }' ),
(14, 'Organization Region' , 'organization_region', '{ type: "string" }' ),
(15, 'Organization Country' , 'organization_country', '{ type: "string" }' ),
(16, 'Organization Postal Code' , 'organization_postal_code', '{ type: "integer" }' ),
(17, 'Organization Phone' , 'organization_phone', '{ type: "integer" }' ),
(18, 'Organization Email' , 'organization_email', '{ type: "string" }' ),
(19, 'Organization Website' , 'organization_website', '{ type: "string" }' ),
(20, 'Organization Mission Statement' , 'organization_mission_statement', '{ type: "string" }' ),
(21, 'Organization Start Date' , 'organization_start_date', '{ type: "string" , format: "date-time" }' ),
(22, 'Organization Fiscal Year End Date' , 'organization_fiscal_year_end_date', '{ type: "string" , format: "date-time" }' ),
(23, 'Organization Fiscal Year End Date - Month' , 'organization_fiscal_year_end_date_month', '{ type: "string" }' ),
(24, 'Organization Fiscal Year End Date - Year' , 'organization_fiscal_year_end_date_year', '{ type: "string" }' ),
(25, 'Organization Operating Budget' , 'organization_operating_budget', '{ type: "number" }' ),
(26, 'Organization Geographic Area' , 'organization_geographic_area', '{ type: "string" }' ),
(27, 'Organization Executive/Administrator' , 'organization_executive_administrator', '{ type: "string" }' ),
(28, 'Organization Executive/Administrator Title' , 'organization_executive_administrator_title', '{ type: "string" }' ),
(29, 'Organization Executive/Administrator Race' , 'organization_executive_administrator_race', '{ type: "string" }' ),
(30, 'Organization Executive/Administrator Gender' , 'organization_executive_administrator_gender', '{ type: "string" }' ),
(31, 'Organization Executive/Administrator Sexual Orientation' , 'organization_executive_administrator_sexual_orientation', '{ type: "string" }' ),
(32, 'Organization Executive/Administrator Disability Status' , 'organization_executive_administrator_disability_status', '{ type: "string" }' ),
(33, 'CEO Review Method' , 'ceo_review_method', '{ type: "string" }' ),
(34, 'Organization Signatory' , 'organization_signatory', '{ type: "string" }' ),
(35, 'Organization Financial Officer' , 'organization_financial_officer', '{ type: "string" }' ),
(36, 'Organization Grants Officer' , 'organization_grants_officer', '{ type: "string" }' ),
(37, 'Organization Banking Contact' , 'organization_banking_contact', '{ type: "string" }' ),
(38, 'Organization Leadership' , 'organization_leadership', '{ type: "string" }' ),
(39, 'Organization Governing Body Type' , 'organization_governing_body_type', '{ type: "string" }' ),
(40, 'Organization Governing Body Term Duration' , 'organization_governing_body_term_duration', '{ type: "string" }' ),
(41, 'Organization Governing Body Number of Terms Permitted' , 'organization_governing_body_number_of_terms_permitted', '{ type: "string" }' ),
(42, 'Organization Governing Body Compensation' , 'organization_governing_body_compensation', '{ type: "string" }' ),
(43, 'Organization Governing Body Financial Oversight' , 'organization_governing_body_financial_oversight', '{ type: "string" }' ),
(44, 'Organization Board Chair' , 'organization_board_chair', '{ type: "string" }' ),
(45, 'Organization Board Chair Title' , 'organization_board_chair_title', '{ type: "string" }' ),
(46, 'Organization Board Members' , 'organization_board_members', '{ type: "integer" }' ),
(47, 'Organization Board Women' , 'organization_board_women', '{ type: "integer" }' ),
(48, 'Organization Board Young Women' , 'organization_board_young_women', '{ type: "integer" }' ),
(49, 'Organization Board Older Women' , 'organization_board_older_women', '{ type: "integer" }' ),
(50, 'Organization Board Senior Women' , 'organization_board_senior_women', '{ type: "integer" }' ),
(51, 'Organization Board Women - Total' , 'organization_board_women_total', '{ type: "integer" }' ),
(52, 'Organization Board Men' , 'organization_board_men', '{ type: "integer" }' ),
(53, 'Organization Board Young Men' , 'organization_board_young_men', '{ type: "integer" }' ),
(54, 'Organization Board Older Men' , 'organization_board_older_men', '{ type: "integer" }' ),
(55, 'Organization Board Senior Men' , 'organization_board_senior_men', '{ type: "integer" }' ),
(56, 'Organization Board Men - Total' , 'organization_board_men_total', '{ type: "integer" }' ),
(57, 'Organization Board Intersex' , 'organization_board_intersex', '{ type: "integer" }' ),
(58, 'Organization Board Heterosexuals' , 'organization_board_heterosexuals', '{ type: "integer" }' ),
(59, 'Organization Board LGBTQ Lesbians' , 'organization_board_lgbtq_lesbians', '{ type: "integer" }' ),
(60, 'Organization Board LGBTQ Gay Men' , 'organization_board_lgbtq_gay_men', '{ type: "integer" }' ),
(61, 'Organization Board LGBTQ Bisexuals' , 'organization_board_lgbtq_bisexuals', '{ type: "integer" }' ),
(62, 'Organization Board LGBTQ Transgender' , 'organization_board_lgbtq_transgender', '{ type: "integer" }' ),
(63, 'Organization Board LGBTQ - Total' , 'organization_board_lgbtq_total', '{ type: "integer" }' ),
(64, 'Organization Board African Descent' , 'organization_board_african_descent', '{ type: "integer" }' ),
(65, 'Organization Board Asian Descent' , 'organization_board_asian_descent', '{ type: "integer" }' ),
(66, 'Organization Board European Descent' , 'organization_board_european_descent', '{ type: "integer" }' ),
(67, 'Organization Board Indigenous Peoples' , 'organization_board_indigenous_peoples', '{ type: "integer" }' ),
(68, 'Organization Board Latin American Descent' , 'organization_board_latin_american_descent', '{ type: "integer" }' ),
(69, 'Organization Board Middle Eastern Descent' , 'organization_board_middle_eastern_descent', '{ type: "integer" }' ),
(70, 'Organization Board Multiracial Descent' , 'organization_board_multiracial_descent', '{ type: "integer" }' ),
(71, 'Organization Paid Staff' , 'organization_paid_staff', '{ type: "integer" }' ),
(72, 'Organization Senior Staff Women' , 'organization_senior_staff_women', '{ type: "integer" }' ),
(73, 'Organization Senior Staff Young Women' , 'organization_senior_staff_young_women', '{ type: "integer" }' ),
(74, 'Organization Senior Staff Older Women' , 'organization_senior_staff_older_women', '{ type: "integer" }' ),
(75, 'Organization Senior Staff Senior Women' , 'organization_senior_staff_senior_women', '{ type: "integer" }' ),
(76, 'Organization Senior Staff Women - Total' , 'organization_senior_staff_women_total', '{ type: "integer" }' ),
(77, 'Organization Senior Staff Men - Men' , 'organization_senior_staff_men_men', '{ type: "integer" }' ),
(78, 'Organization Senior Staff Men - Young Men' , 'organization_senior_staff_men_young_men', '{ type: "integer" }' ),
(79, 'Organization Senior Staff Men - Older Men' , 'organization_senior_staff_men_older_men', '{ type: "integer" }' ),
(80, 'Organization Senior Staff Men - Senior Men' , 'organization_senior_staff_men_senior_men', '{ type: "integer" }' ),
(81, 'Organization Senior Staff Men - Total' , 'organization_senior_staff_men_total', '{ type: "integer" }' ),
(82, 'Organization Senior Staff Intersex People' , 'organization_senior_staff_intersex_people', '{ type: "integer" }' ),
(83, 'Organization Senior Staff Heterosexuals' , 'organization_senior_staff_heterosexuals', '{ type: "integer" }' ),
(84, 'Organization Senior Staff LGBTQ Lesbians' , 'organization_senior_staff_lgbtq_lesbians', '{ type: "integer" }' ),
(85, 'Organization Senior Staff LGBTQ Gay Men' , 'organization_senior_staff_lgbtq_gay_men', '{ type: "integer" }' ),
(86, 'Organization Senior Staff LGBTQ Bisexuals' , 'organization_senior_staff_lgbtq_bisexuals', '{ type: "integer" }' ),
(87, 'Organization Senior Staff LGBTQ Transgender' , 'organization_senior_staff_lgbtq_transgender', '{ type: "integer" }' ),
(88, 'Organization Senior Staff LGBTQ - Total' , 'organization_senior_staff_lgbtq_total', '{ type: "integer" }' ),
(89, 'Organization Senior Staff African Descent' , 'organization_senior_staff_african_descent', '{ type: "integer" }' ),
(90, 'Organization Senior Staff Asian Descent' , 'organization_senior_staff_asian_descent', '{ type: "integer" }' ),
(91, 'Organization Senior Staff European Descent' , 'organization_senior_staff_european_descent', '{ type: "integer" }' ),
(92, 'Organization Senior Staff Indigenous Peoples' , 'organization_senior_staff_indigenous_peoples', '{ type: "integer" }' ),
(93, 'Organization Senior Staff Latin American Descent' , 'organization_senior_staff_latin_american_descent', '{ type: "integer" }' ),
(94, 'Organization Senior Staff Middle Eastern Descent' , 'organization_senior_staff_middle_eastern_descent', '{ type: "integer" }' ),
(95, 'Organization Senior Staff Multiracial Descent' , 'organization_senior_staff_multiracial_descent', '{ type: "integer" }' ),
(96, 'Organization Conflict of Interest Policy' , 'organization_conflict_of_interest_policy', '{ type: "string" }' ),
(97, 'Organization Workplace Issues' , 'organization_workplace_issues', '{ type: "string" }' ),
(98, 'Organization Whistleblower Policy' , 'organization_whistleblower_policy', '{ type: "string" }' ),
(99, 'Organization Financial Statements' , 'organization_financial_statements', '{ type: "string" }' ),
(100, 'Organization Legal Documents' , 'organization_legal_documents', '{ type: "string" }' ),
(101, 'Proposal Date' , 'proposal_date', '{ type: "string", format: "date-time"  }' ),
(102, 'Proposal Name' , 'proposal_name', '{ type: "string" }' ),
(103, 'Proposal Title' , 'proposal_title', '{ type: "string" }' ),
(104, 'Proposal Type' , 'proposal_type', '{ type: "string" }' ),
(105, 'Proposal Focus' , 'proposal_focus', '{ type: "string" }' ),
(106, 'Proposal Summary' , 'proposal_summary', '{ type: "string" }' ),
(107, 'Proposal Primary Contact Name' , 'proposal_primary_contact_name', '{ type: "string" }' ),
(108, 'Proposal Primary Contact Title' , 'proposal_primary_contact_title', '{ type: "string" }' ),
(109, 'Proposal Primary Contact Phone' , 'proposal_primary_contact_phone', '{ type: "string" }' ),
(110, 'Proposal Primary Contact Email' , 'proposal_primary_contact_email', '{ type: "string" }' ),
(111, 'Proposal Submitter Prefix' , 'proposal_submitter_prefix', '{ type: "string" }' ),
(112, 'Proposal Submitter First Name' , 'proposal_submitter_first_name', '{ type: "string" }' ),
(113, 'Proposal Submitter Middle Initial' , 'proposal_submitter_middle_initial', '{ type: "string" }' ),
(114, 'Proposal Submitter Last Name' , 'proposal_submitter_last_name', '{ type: "string" }' ),
(115, 'Proposal Submitter Suffix' , 'proposal_submitter_suffix', '{ type: "string" }' ),
(116, 'Proposal Submitter Title' , 'proposal_submitter_title', '{ type: "string" }' ),
(117, 'Proposal Submitter Phone' , 'proposal_submitter_phone', '{ type: "string" }' ),
(118, 'Proposal Submitter Extension' , 'proposal_submitter_extension', '{ type: "string" }' ),
(119, 'Proposal Submitter Mobile Phone' , 'proposal_submitter_mobile_phone', '{ type: "string" }' ),
(120, 'Proposal Submitter Email' , 'proposal_submitter_email', '{ type: "string" }' ),
(121, 'Proposal Submitter Street Address 1' , 'proposal_submitter_street_address_1', '{ type: "string" }' ),
(122, 'Proposal Submitter Street Address 2' , 'proposal_submitter_street_address_2', '{ type: "string" }' ),
(123, 'Proposal Submitter City/Town' , 'proposal_submitter_city_town', '{ type: "string" }' ),
(124, 'Proposal Submitter State/Province' , 'proposal_submitter_state_province', '{ type: "string" }' ),
(125, 'Proposal Submitter State Code' , 'proposal_submitter_state_code', '{ type: "string" }' ),
(126, 'Proposal Submitter Region' , 'proposal_submitter_region', '{ type: "string" }' ),
(127, 'Proposal Submitter Zip Code' , 'proposal_submitter_zip_code', '{ type: "string" }' ),
(128, 'Proposal Submitter Name' , 'proposal_submitter_name', '{ type: "string" }' ),
(129, 'Proposal Amount Requested' , 'proposal_amount_requested', '{ type: "number" }' ),
(130, 'Proposal Funding Category' , 'proposal_funding_category', '{ type: "string" }' ),
(131, 'Proposal Budget' , 'proposal_budget', '{ type: "number" }' ),
(132, 'Proposal Budget Narrative' , 'proposal_budget_narrative', '{ type: "string" }' ),
(133, 'Proposal Project Budget' , 'proposal_project_budget', '{ type: "number" }' ),
(134, 'Proposal Fiscal Sponsor?' , 'proposal_fiscal_sponsor', '{ type: "boolean" }' ),
(135, 'Proposal Fiscal Sponsor Information' , 'proposal_fiscal_sponsor_information', '{ type: "string" }' ),
(136, 'Proposal Fiscal Sponsor Name' , 'proposal_fiscal_sponsor_name', '{ type: "string" }' ),
(137, 'Proposal Fiscal Sponsor EIN' , 'proposal_fiscal_sponsor_ein', '{ type: "string" }' ),
(138, 'Proposal Fiscal Sponsor Contact First Name' , 'proposal_fiscal_sponsor_contact_first_name', '{ type: "string" }' ),
(139, 'Proposal Fiscal Sponsor Cantact Last Name' , 'proposal_fiscal_sponsor_cantact_last_name', '{ type: "string" }' ),
(140, 'Proposal Fiscal Sponsor Contact Email' , 'proposal_fiscal_sponsor_contact_email', '{ type: "string" }' ),
(141, 'Proposal Regrant' , 'proposal_regrant', '{ type: "string" }' ),
(142, 'Proposal Regrant Subgrantees' , 'proposal_regrant_subgrantees', '{ type: "string" }' ),
(143, 'Proposal Subgrantee List' , 'proposal_subgrantee_list', '{ type: "string" }' ),
(144, 'Proposal Expenditure Responsibility' , 'proposal_expenditure_responsibility', '{ type: "string" }' ),
(145, 'Proposal Equivalency Determination' , 'proposal_equivalency_determination', '{ type: "string" }' ),
(146, 'Proposal Tipping Amount' , 'proposal_tipping_amount', '{ type: "number" }' ),
(147, 'Proposal Funding Summary' , 'proposal_funding_summary', '{ type: "string" }' ),
(148, 'Proposal Start Date' , 'proposal_start_date', '{ type: "string", format: "date-time"  }' ),
(149, 'Proposal End Date' , 'proposal_end_date', '{ type: "string", format: "date-time"  }' ),
(150, 'Proposal Duration' , 'proposal_duration', '{ type: "string" }' ),
(151, 'Proposal Location of Work' , 'proposal_location_of_work', '{ type: "string" }' ),
(152, 'Proposal Age Group' , 'proposal_age_group', '{ type: "string" }' ),
(153, 'Proposal Ethnicity' , 'proposal_ethnicity', '{ type: "string" }' ),
(154, 'Proposal Need' , 'proposal_need', '{ type: "string" }' ),
(155, 'Proposal Activities' , 'proposal_activities', '{ type: "string" }' ),
(156, 'Proposal Tactics and Methods' , 'proposal_tactics_and_methods', '{ type: "string" }' ),
(157, 'Proposal Strategy' , 'proposal_strategy', '{ type: "string" }' ),
(158, 'Proposal Organizational Strengths' , 'proposal_organizational_strengths', '{ type: "string" }' ),
(159, 'Proposal Equity' , 'proposal_equity', '{ type: "string" }' ),
(160, 'Proposal Engagement' , 'proposal_engagement', '{ type: "string" }' ),
(161, 'Proposal Challenges and Risks' , 'proposal_challenges_and_risks', '{ type: "string" }' ),
(162, 'Proposal Related Programs' , 'proposal_related_programs', '{ type: "string" }' ),
(163, 'Proposal Supplemental Information' , 'proposal_supplemental_information', '{ type: "string" }' ),
(164, 'Proposal Results' , 'proposal_results', '{ type: "string" }' ),
(165, 'Proposal Project Outcomes' , 'proposal_project_outcomes', '{ type: "string" }' ),
(166, 'Proposal Anticipated Impact' , 'proposal_anticipated_impact', '{ type: "string" }' ),
(167, 'Proposal Sustainability' , 'proposal_sustainability', '{ type: "string" }' ),
(168, 'Proposal IRB Approval Needed' , 'proposal_irb_approval_needed', '{ type: "string" }' ),
(169, 'Proposal IRB Approval Obtained' , 'proposal_irb_approval_obtained', '{ type: "string" }' ),
(170, 'Organization Lobbying Activities' , 'organization_lobbying_activities', '{ type: "string" }' ),
(171, 'Proposal Legislation' , 'proposal_legislation', '{ type: "string" }' ),
(172, 'Proposal Lobbying more than Grant' , 'proposal_lobbying_more_than_grant', '{ type: "boolean" }' ),
(173, 'Review Amount Recommended' , 'review_amount_recommended', '{ type: "string" }' ),
(174, 'Review Comments to Applicant' , 'review_comments_to_applicant', '{ type: "string" }' ),
(175, 'Review Additional Comments' , 'review_additional_comments', '{ type: "string" }' ),
(176, 'Review Grant Agreement Date' , 'review_grant_agreement_date', '{ type: "string", format: "date-time"  }' ),
(177, 'Review Start Date' , 'review_start_date', '{ type: "string", format: "date-time"  }' ),
(178, 'Review End Date' , 'review_end_date', '{ type: "string", format: "date-time"  }' ),
(179, 'Review Close Date' , 'review_close_date', '{ type: "string", format: "date-time"  }' ),
(180, 'Review  Submission ID' , 'review_submission_id', '{ type: "integer" }' ),
(181, 'Review Status' , 'review_status', '{ type: "string" }' ),
(182, 'Review Date' , 'review_date', '{ type: "string", format: "date-time"  }' ),
(183, 'Review Submission URL' , 'review_submission_url', '{ type: "string" }' ),
(184, 'Review Labels' , 'review_labels', '{ type: "string" }' ),
(185, 'Review Affiliate ID' , 'review_affiliate_id', '{ type: "integer" }' ),
(186, 'Review Assigned To' , 'review_assigned_to', '{ type: "string" }' ),
(187, 'Review Current Review Stage' , 'review_current_review_stage', '{ type: "string" }' ),
(188, 'Review Total Score' , 'review_total_score', '{ type: "integer" }' ),
(189, 'Review Average Score' , 'review_average_score', '{ type: "integer" }' ),
(190, 'Review Gallery Votes' , 'review_gallery_votes', '{ type: "integer" }' ),
(191, 'Review Total Votes' , 'review_total_votes', '{ type: "integer" }' ),
(192, 'PDC Share Data' , 'pdc_share_data', '{ type: "string" }' ),
(193, 'What is the overall CC score (could have decmials)' , 'what_is_the_overall_cc_score', '{ type: "number" }' ),
(194, 'Rounded CC score to remove decimals' , 'rounded_cc_score_to_remove_decimals', '{ type: "integer" }' ),
(195, 'Date Record was created' , 'date_record_was_created', '{ type: "string", format: "date-time"  }' ),
(196, 'Date Record was published' , 'date_record_was_published', '{ type: "string", format: "date-time"  }' ),
(197, 'End date for the time period covered by this tax form for the rated fiscal year' , 'end_date_for_the_time_period_covered_by_this_tax_form_for_the_rated_fiscal_year', '{ type: "string", format: "date-time"  }' ),
(198, 'Did they pass Board Size Metric' , 'did_they_pass_board_size_metric', '{ type: "boolean" }' ),
(199, 'Did they pass Board Ratio Metric' , 'did_they_pass_board_ratio_metric', '{ type: "boolean" }' ),
(200, 'Did they pass URL on 990 Metric' , 'did_they_pass_url_on_990_metric', '{ type: "boolean" }' ),
(201, 'Did they pass board minutes Metric' , 'did_they_pass_board_minutes_metric', '{ type: "boolean" }' ),
(202, 'Did they pass whistleblower Metric' , 'did_they_pass_whistleblower_metric', '{ type: "boolean" }' ),
(203, 'Did they pass conflict of interest Metric' , 'did_they_pass_conflict_of_interest_metric', '{ type: "boolean" }' ),
(204, 'Did they pass Document Retention Metric' , 'did_they_pass_document_retention_metric', '{ type: "boolean" }' ),
(205, 'Did they pass Audit/Review Metric' , 'did_they_pass_audit_review_metric', '{ type: "boolean" }' ),
(206, 'Rounded Total Score for FA' , 'rounded_total_score_for_fa', '{ type: "integer" }' ),
(207, 'Do they have an audit' , 'do_they_have_an_audit', '{ type: "boolean" }' ),
(208, 'Do they have board minutes' , 'do_they_have_board_minutes', '{ type: "boolean" }' ),
(209, 'Do they have a whistleblower policy' , 'do_they_have_a_whistleblower_policy', '{ type: "boolean" }' ),
(210, 'Do they have a compliation or review' , 'do_they_have_a_compliation_or_review', '{ type: "boolean" }' ),
(211, 'Do they have a conflict of interest policy' , 'do_they_have_a_conflict_of_interest_policy', '{ type: "boolean" }' ),
(212, 'Do they have a document retention policy' , 'do_they_have_a_document_retention_policy', '{ type: "boolean" }' ),
(213, 'Is their URL listed on the 990' , 'is_their_url_listed_on_the_990', '{ type: "boolean" }' ),
(214, 'What is the percent of their independant board' , 'what_is_the_percent_of_their_independant_board', '{ type: "number" }' ),
(215, 'Rating year' , 'rating_year', '{ type: "string" }' ),
(216, 'Date F&A beacon published' , 'date_f&a_beacon_published', '{ type: "string", format: "date-time"  }' ),
(217, 'Total Finace score' , 'total_finace_score', '{ type: "integer" }' ),
(218, 'Total Accountability Score' , 'total_accountability_score', '{ type: "integer" }' ),
(219, 'Impact and Results Score' , 'impact_and_results_score', '{ type: "integer" }' ),
(220, 'Cost per outcome statement' , 'cost_per_outcome_statement', '{ type: "integer" }' ),
(221, 'If it is cost-effective, highly cost-effective or not cost effective' , 'if_it_is_cost_effective_highly_cost_effective_or_not_cost_effective', '{ type: "string" }' ),
(222, 'Program categories' , 'program_categories', '{ type: "string" }' ),
(223, 'summary of the activities' , 'summary_of_the_activities', '{ type: "string" }' ),
(224, 'Who they serve' , 'who_they_serve', '{ type: "string" }' ),
(225, 'Data time period' , 'data_time_period_', '{ type: "string" }' ),
(226, 'Outcome metric measures' , 'outcome_metric_measures', '{ type: "string" }' ),
(227, 'How they calculated counterfactual' , 'how_they_calculated_counterfactual_', '{ type: "string" }' ),
(228, 'data source for calculation' , 'data_source_for_calculation', '{ type: "string" }' ),
(229, 'the arithmetic for the cost calculation' , 'the_arithmetic_for_the_cost_calculation', '{ type: "string" }' ),
(230, 'Impact calcuation.' , 'impact_calcuation', '{ type: "string" }' ),
(231, 'Benchmark for comparision' , 'benchmark_for_comparision', '{ type: "string" }' ),
(232, 'Date impact rating was created' , 'date_impact_rating_was_created', '{ type: "string" }' ),
(233, 'Score for mission statement' , 'score_for_mission_statement', '{ type: "integer" }' ),
(234, 'Score for vision statement' , 'score_for_vision_statement', '{ type: "integer" }' ),
(235, 'Score for goals score' , 'score_for_goals_score', '{ type: "integer" }' ),
(236, 'Overall Strategy score' , 'overall_strategy_score', '{ type: "integer" }' ),
(237, 'Leadership metrics investment_score' , 'leadership_metrics_investment_score', '{ type: "integer" }' ),
(238, 'Leadership metrics external focus_score' , 'leadership_metrics_external_focus_score', '{ type: "integer" }' ),
(239, 'Overal leadership score' , 'overal_leadership_score', '{ type: "integer" }' ),
(240, 'Adaptablity metrics- Score' , 'adaptablity_metrics_score', '{ type: "integer" }' ),
(241, 'Overall adaptablity score' , 'overall_adaptablity_score', '{ type: "integer" }' ),
(242, 'Total Leadership and Adaptablity score' , 'total_leadership_and_adaptablity_score', '{ type: "integer" }' ),
(243, 'Created L&A score date' , 'created_l&a_score_date', '{ type: "string", format: "date-time"  }' ),
(244, 'Is this an overall Encompass passing rating' , 'is_this_an_overall_encompass_passing_rating', '{ type: "boolean" }' ),
(245, 'Is this rating eligible for publishing' , 'is_this_rating_eligible_for_publishing', '{ type: "boolean" }' ),
(246, 'Overall Encompass Score (including decimals)' , 'overall_encompass_score_decimal', '{ type: "number" }' ),
(247, 'Overall Encompass Score (rounded to whole numbers)' , 'overall_encompass_score_rounded', '{ type: "integer" }' ),
(248, 'Total points avaiable in Encompass' , 'total_points_avaiable_in_encompass', '{ type: "integer" }' ),
(249, 'When was this Overall Rating created' , 'when_was_this_overall_rating_created', '{ type: "string", format: "date-time"  }' ),
(250, 'Category of Charity (Highest level of cause categorization)' , 'category_of_charity', '{ type: "string" }' ),
(251, 'Cause of Charity (Mid Level of cause categorization)' , 'cause_of_charity', '{ type: "string" }' ),
(252, 'Date of latest source' , 'date_of_latest_source', '{ type: "string", format: "date-time"  }' ),
(253, 'Is there a donor advisory on this charity?' , 'is_there_a_donor_advisory_on_this_charity', '{ type: "boolean" }' ),
(254, 'Text of the donor advisory message in html' , 'text_of_the_donor_advisory_message_in_html', '{ type: "string" }' ),
(255, 'Date the donor advisory went live' , 'date_the_donor_advisory_went_live', '{ type: "string", format: "date-time"  }' ),
(256, 'Date Current CEO was last verified' , 'date_current_ceo_was_last_verified', '{ type: "string", format: "date-time"  }' ),
(257, 'Web location of pro-forma 990s to handle Pharmaceutical valuation adjustments' , 'web_location_of_proforma_990s_to_handle_pharmaceutical_valuation_adjustments', '{ type: "string" }' ),
(258, 'Fiscal Year of Financial Rating' , 'fiscal_year_of_financial_rating', '{ type: "string" }' ),
(259, 'Fundraising Efficiency Amount' , 'fundraising_efficiency_amount', '{ type: "integer" }' ),
(260, 'Fundraising Expense Ratio' , 'fundraising_expense_ratio', '{ type: "string" }' ),
(261, 'Program Expense Ratio' , 'program_expense_ratio', '{ type: "string" }' ),
(262, 'Administrative Expense Ratio' , 'administrative_expense_ratio', '{ type: "string" }' ),
(263, 'Working Capital Ratio' , 'working_capital_ratio', '{ type: "string" }' ),
(264, 'Fundraising Efficiency Score' , 'fundraising_efficiency_score', '{ type: "integer" }' ),
(265, 'Fundraising Expense Score' , 'fundraising_expense_score', '{ type: "integer" }' ),
(266, 'Program Expense Score' , 'program_expense_score', '{ type: "integer" }' ),
(267, 'Administrative Expense Score' , 'administrative_expense_score', '{ type: "integer" }' ),
(268, 'Primary Revenue Growth Score' , 'primary_revenue_growth_score', '{ type: "integer" }' ),
(269, 'Program Expense Growth Score' , 'program_expense_growth_score', '{ type: "integer" }' ),
(270, 'Working Capital Score' , 'working_capital_score', '{ type: "integer" }' ),
(271, 'Score in the Financial dimension' , 'score_in_the_financial_dimension', '{ type: "integer" }' ),
(272, 'Score in the A&T dimension' , 'score_in_the_a&t_dimension', '{ type: "integer" }' ),
(273, 'Rating in the A&T dimension' , 'rating_in_the_a&t_dimension', '{ type: "integer" }' ),
(274, 'Score in the Results dimension' , 'score_in_the_results_dimension', '{ type: "integer" }' ),
(275, 'Rating in the Results Dimension' , 'rating_in_the_results_dimension', '{ type: "integer" }' ),
(276, 'Overall Score' , 'overall_score', '{ type: "integer" }' ),
(277, 'Overall Rating' , 'overall_rating', '{ type: "integer" }' ),
(278, 'Yes/No indicator: This rating is a Donor Advisory' , 'yes_no_indicator_this_rating_is_a_donor_advisory', '{ type: "boolean" }' );

-- Due to 'OVERRIDING SYSTEM VALUE' above, the sequence needs to be updated:
SELECT SETVAL(
  pg_get_serial_sequence('canonical_fields', 'id'),
  COALESCE(max(id), 1))
FROM canonical_fields;
