ALTER TABLE db_operation_audit_logs RENAME TO service_query_audit_logs;
ALTER TABLE service_query_audit_logs RENAME CONSTRAINT
db_operation_audit_logs_user_keycloak_user_id_fkey TO
service_query_audit_logs_user_keycloak_user_id_fkey;
ALTER INDEX db_operation_audit_logs_action_tstamp_stm_idx
RENAME TO service_query_audit_logs_action_tstamp_stm_idx;
ALTER INDEX db_operation_audit_logs_action_user_keycloak_user_id_idx
RENAME TO service_query_audit_logs_action_user_keycloak_user_id_idx;
