volumes:
  s3:
    external: false
  db:
    external: false
services:
  # There is no great way to avoid root-owned volumes except an init container
  # which itself runs as root, sets user/group on volumes, then exits.
  # I suppose it could be part of post_start, but there is no guarantee that the
  # command will run before the server attempts to start, whereas this way does
  # have such a guarantee.
  init-volumes:
    image: docker.io/debian:latest
    volumes:
      - s3:/data/s3
      - db:/data/db
    command:
      - /bin/sh
      - -ec
      - |
        chown ${UID:-1000}:${GID:-${UID:-1000}} -R /data/s3
        chown 999:999 -R /data/db
  s3:
    image: docker.io/minio/minio:latest
    user: ${UID:-1000}:${GID:-${UID:-1000}}
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: s3key
      MINIO_ROOT_PASSWORD: s3secret
    volumes:
      - s3:/data/s3
    command: ["server", "--console-address", ":9001", "/data/s3"]
    post_start:
      # Post-start hook runs right away and yet has no timing guarantee.
      # Sleep to give the server a chance to start then add an alias and bucket.
      - command:
        - /bin/sh
        - -ec
        - |
          sleep 2
          mc alias set pdc http://s3:9000/ s3key s3secret
          mc mb pdc/service
        user: ${UID:-1000}
    healthcheck:
      # Check for the above-created bucket to exist.
      test: ["CMD", "mc", "stat", "pdc/service"]
      interval: 4s
    restart: always
    depends_on:
      init-volumes:
        condition: service_completed_successfully
  web:
    image: ghcr.io/philanthropydatacommons/service:latest
    # The image contains user 902
    user: 902:902
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - PGHOST=database
      - PGUSER=pdc
      - PGPASSWORD=pdc
      - PGDATABASE=pdc
      - PGPORT=5432
      - AUTH_SERVER_ISSUER=http://localhost:8080/realms/pdc
      - OPENAPI_DOCS_AUTH_CLIENT_ID=pdc-openapi-docs
      - S3_ACCESS_KEY_ID=s3key
      - S3_ACCESS_SECRET=s3secret
      - S3_ENDPOINT=http://localhost:9000
      - S3_PATH_STYLE=false
      - S3_REGION=us-east-1
      - S3_BUCKET=pdc/service
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://web:3000"]
      interval: 10s
    depends_on:
      database:
        condition: service_healthy
      s3:
        condition: service_healthy
      auth:
        condition: service_healthy
    restart: always
  database:
    image: docker.io/postgres:17
    environment:
      POSTGRES_USER: pdc
      POSTGRES_PASSWORD: pdc
      POSTGRES_INITDB_ARGS: "--username=pdc --allow-group-access"
      PGDATA: /data/db
    # The image contains user 999
    user: 999:999
    shm_size: 128mb
    volumes:
      - db:/data/db
    post_start:
      # Sleep to give the server a chance to start then add a Keycloak DB.
      - command:
        - /bin/sh
        - -ec
        - |
          sleep 8
          psql -U pdc -d postgres -c 'create database keycloak owner pdc;'
        user: "999"
    healthcheck:
      # Wait for the Keycloak DB to be available.
      test: ["CMD", "psql", "-U", "pdc", "-d", "keycloak", "-c", "select 1;"]
      interval: 15s
    restart: always
    command: ["postgres"]
    depends_on:
      init-volumes:
        condition: service_completed_successfully
  auth:
    image: docker.io/keycloak/keycloak:latest
    user: ${UID:-1000}:${GID:-${UID:-1000}}
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: database
      KC_DB_USERNAME: pdc
      KC_DB_PASSWORD: pdc
      KC_HEALTH_ENABLED: true
    healthcheck:
      test: |
        /bin/sh
        -ec
        /opt/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080/ --realm master --user admin --password admin
        /opt/keycloak/bin/kcadm.sh get http://localhost:9000/health
      interval: 15s
    command: ["start-dev"]
    depends_on:
      database:
        condition: service_healthy
    post_start:
      # Sleep to give the server a (long!) chance to start then add a Realm.
      - command:
        - /bin/bash
        - -ecx
        - |
          sleep 90
          cd /opt/keycloak/bin
          ./kcadm.sh config credentials --server http://localhost:8080/ --realm master --user admin --password admin
          ./kcadm.sh create realms -b '{"realm":"pdc","enabled":"true"}'
          ./kcadm.sh create users -r pdc -s username='dev@pdc.local' -s email='dev@pdc.local' -s emailVerified='true' -s enabled='true' -i > user_id
          ./kcadm.sh set-password -r pdc --username 'dev@pdc.local' --new-password 'password'
          ./kcadm.sh create clients -r pdc \
          -s clientId='pdc-openapi-docs' \
          -s name='PDC OpenAPI Documentation' \
          -s description='The OpenAPI documentation of the PDC API served by the back-end service implementation. These are publicly accessible but have an authorize button that uses OIDC to authenticate.' \
          -s rootUrl='http://localhost:3000' \
          -s redirectUris='["http://localhost:3000/*"]' \
          -s publicClient='true' -s standardFlowEnabled='true' \
          -s implicitFlowEnabled='false' -s directAccessGrantsEnabled='false' \
          -s serviceAccountsEnabled='false' \
          -s authorizationServicesEnabled='false' \
          -s webOrigins='+'
          ./kcadm.sh create roles -r pdc -s name='pdc-admin' -s description='PDC Users with application-level Administrative privileges.'
          ./kcadm.sh create groups -r pdc -s name='pdc-admin' -s realmRoles='["manage-users","query-users","view-users","pdc-admin"]' -i > admin_group_id
          ./kcadm.sh update users/$(cat user_id)/groups/$(cat admin_group_id) -r pdc -s realm pdc -s userId=$(cat user_id) -s groupId=$(cat admin_group_id) -n
        user: ${UID:-1000}
