alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
  - rule: DEPLOYMENT_LIVE
databases:
  - cluster_name: db-example-pdc-service
    db_name: pdc
    db_user: pdc
    engine: PG
    name: db-example-pdc-service
    production: true
    version: '16'
domains:
  - domain: example.com
    type: PRIMARY
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: service
      match:
        path:
          prefix: /
name: pdc-service
region: example-region
services:
  - envs:
      - key: AUTH_SERVER_ISSUER
        scope: RUN_AND_BUILD_TIME
        value: https://auth.example.com/realms/pdc
      - key: OPENAPI_DOCS_AUTH_CLIENT_ID
        scope: RUN_AND_BUILD_TIME
        value: pdc-openapi-docs
      - key: HOST
        scope: RUN_AND_BUILD_TIME
        value: 0.0.0.0
      - key: S3_ACCESS_KEY_ID
        scope: RUN_AND_BUILD_TIME
        value: your_key_id
      - key: S3_BUCKET
        scope: RUN_AND_BUILD_TIME
        value: your-bucket-name
      - key: S3_ENDPOINT
        scope: RUN_AND_BUILD_TIME
        value: https://s3.example.com
      - key: S3_PATH_STYLE
        scope: RUN_AND_BUILD_TIME
        value: 'false'
      - key: S3_REGION
        scope: RUN_AND_BUILD_TIME
        value: us-east-1
      - key: PGHOST
        scope: RUN_AND_BUILD_TIME
        value: ${db-example-pdc-service.HOSTNAME}
      - key: PGPORT
        scope: RUN_AND_BUILD_TIME
        value: ${db-example-pdc-service.PORT}
      - key: PGUSER
        scope: RUN_AND_BUILD_TIME
        value: ${db-example-pdc-service.USERNAME}
      - key: PGPASSWORD
        scope: RUN_AND_BUILD_TIME
        value: ${db-example-pdc-service.PASSWORD}
      - key: PGSSLMODE
        scope: RUN_AND_BUILD_TIME
        value: no-verify
      - key: PGDATABASE
        scope: RUN_AND_BUILD_TIME
        value: ${db-example-pdc-service.DATABASE}
      - key: S3_ACCESS_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: your_key_secret
    health_check:
      http_path: /
    http_port: 8080
    image:
      registry: ghcr.io
      registry_type: GHCR
      repository: philanthropydatacommons/service
      tag: latest
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    name: service
