-- Use the included INSERT statement to seed base fields data.

-- This script helps get a development database started with some base fields.

-- Usage example 1: `psql -d pdc -U pdc -p 5432 -f 0001-insert-base_fields.sql`
-- Usage example 2: `cat 0001-insert-base_fields.sql` then copy/paste into a `psql` session.

-- If you get a `violates unique constraint` error, you might already have run the script once.
-- If you get the `violates unique constraint` error and didn't run it, you have a conflicting row
-- in your database instance in the base_fields table. The error `DETAIL` should help you find
-- the problem row. Try `DELETE FROM base_fields WHERE short_code='the_short_code'` to remove
-- the existing row. If such a `DELETE` fails due to a foreign key reference, that means the
-- base field is already used in an application form and should probably not be removed unless
-- you are OK with first removing the application form and its dependent data in proposals,
-- proposal versions, and proposal field values.

-- The SQL in this file was generated from a spreadsheet as input to a script here:
-- https://github.com/PhilanthropyDataCommons/data-scripts/commit/2af7a7109017f7d43ff7593660dbdce44732d126

INSERT INTO base_fields (label, short_code, data_type) VALUES
('Organization Name', 'organization_name', '{ "type": "string" }' ),
('Organization Legal Name' , 'organization_legal_name', '{ "type": "string" }' ),
('Organization DBA Name' , 'organization_dba_name', '{ "type": "string" }' ),
('Organization Acronym' , 'organization_acronym', '{ "type": "string" }' ),
('Organization ID' , 'organization_id', '{ "type": "string" }' ),
('Organization Charitable Organization' , 'organization_charitable_organization', '{ "type": "string" }' ),
('Organization Entity Type' , 'organization_entity_type', '{ "type": "string" }' ),
('Organization Tax ID' , 'organization_tax_id', '{ "type": "string" }' ),
('Organization Tax Status Date' , 'organization_tax_status_date', '{ "type": "string", "format": "date-time" }' ),
('Organization Street Address 1' , 'organization_street_address_1', '{ "type": "string" }' ),
('Organization Street Address 2' , 'organization_street_address_2', '{ "type": "string" }' ),
('Organization City' , 'organization_city', '{ "type": "string" }' ),
('Organization County' , 'organization_county', '{ "type": "string" }' ),
('Organization State/Province' , 'organization_state_province', '{ "type": "string" }' ),
('Organization Region' , 'organization_region', '{ "type": "string" }' ),
('Organization Country' , 'organization_country', '{ "type": "string" }' ),
('Organization Postal Code' , 'organization_postal_code', '{ "type": "integer" }' ),
('Organization Phone' , 'organization_phone', '{ "type": "integer" }' ),
('Organization Email' , 'organization_email', '{ "type": "string" }' ),
('Organization Website' , 'organization_website', '{ "type": "string" }' ),
('Organization Mission Statement' , 'organization_mission_statement', '{ "type": "string" }' ),
('Organization Start Date' , 'organization_start_date', '{ "type": "string", "format": "date-time" }' ),
('Organization Fiscal Year End Date' , 'organization_fiscal_year_end_date', '{ "type": "string", "format": "date-time" }' ),
('Organization Fiscal Year End Date - Month' , 'organization_fiscal_year_end_date_month', '{ "type": "string" }' ),
('Organization Fiscal Year End Date - Year' , 'organization_fiscal_year_end_date_year', '{ "type": "string" }' ),
('Organization Operating Budget' , 'organization_operating_budget', '{ "type": "number" }' ),
('Organization Geographic Area' , 'organization_geographic_area', '{ "type": "string" }' ),
('Organization Executive/Administrator' , 'organization_executive_administrator', '{ "type": "string" }' ),
('Organization Executive/Administrator Title' , 'organization_executive_administrator_title', '{ "type": "string" }' ),
('Organization Executive/Administrator Race' , 'organization_executive_administrator_race', '{ "type": "string" }' ),
('Organization Executive/Administrator Gender' , 'organization_executive_administrator_gender', '{ "type": "string" }' ),
('Organization Executive/Administrator Sexual Orientation' , 'organization_executive_administrator_sexual_orientation', '{ "type": "string" }' ),
('Organization Executive/Administrator Disability Status' , 'organization_executive_administrator_disability_status', '{ "type": "string" }' ),
('CEO Review Method' , 'ceo_review_method', '{ "type": "string" }' ),
('Organization Signatory' , 'organization_signatory', '{ "type": "string" }' ),
('Organization Financial Officer' , 'organization_financial_officer', '{ "type": "string" }' ),
('Organization Grants Officer' , 'organization_grants_officer', '{ "type": "string" }' ),
('Organization Banking Contact' , 'organization_banking_contact', '{ "type": "string" }' ),
('Organization Leadership' , 'organization_leadership', '{ "type": "string" }' ),
('Organization Governing Body Type' , 'organization_governing_body_type', '{ "type": "string" }' ),
('Organization Governing Body Term Duration' , 'organization_governing_body_term_duration', '{ "type": "string" }' ),
('Organization Governing Body Number of Terms Permitted' , 'organization_governing_body_number_of_terms_permitted', '{ "type": "string" }' ),
('Organization Governing Body Compensation' , 'organization_governing_body_compensation', '{ "type": "string" }' ),
('Organization Governing Body Financial Oversight' , 'organization_governing_body_financial_oversight', '{ "type": "string" }' ),
('Organization Board Chair' , 'organization_board_chair', '{ "type": "string" }' ),
('Organization Board Chair Title' , 'organization_board_chair_title', '{ "type": "string" }' ),
('Organization Board Members' , 'organization_board_members', '{ "type": "integer" }' ),
('Organization Board Women' , 'organization_board_women', '{ "type": "integer" }' ),
('Organization Board Young Women' , 'organization_board_young_women', '{ "type": "integer" }' ),
('Organization Board Older Women' , 'organization_board_older_women', '{ "type": "integer" }' ),
('Organization Board Senior Women' , 'organization_board_senior_women', '{ "type": "integer" }' ),
('Organization Board Women - Total' , 'organization_board_women_total', '{ "type": "integer" }' ),
('Organization Board Men' , 'organization_board_men', '{ "type": "integer" }' ),
('Organization Board Young Men' , 'organization_board_young_men', '{ "type": "integer" }' ),
('Organization Board Older Men' , 'organization_board_older_men', '{ "type": "integer" }' ),
('Organization Board Senior Men' , 'organization_board_senior_men', '{ "type": "integer" }' ),
('Organization Board Men - Total' , 'organization_board_men_total', '{ "type": "integer" }' ),
('Organization Board Intersex' , 'organization_board_intersex', '{ "type": "integer" }' ),
('Organization Board Heterosexuals' , 'organization_board_heterosexuals', '{ "type": "integer" }' ),
('Organization Board LGBTQ Lesbians' , 'organization_board_lgbtq_lesbians', '{ "type": "integer" }' ),
('Organization Board LGBTQ Gay Men' , 'organization_board_lgbtq_gay_men', '{ "type": "integer" }' ),
('Organization Board LGBTQ Bisexuals' , 'organization_board_lgbtq_bisexuals', '{ "type": "integer" }' ),
('Organization Board LGBTQ Transgender' , 'organization_board_lgbtq_transgender', '{ "type": "integer" }' ),
('Organization Board LGBTQ - Total' , 'organization_board_lgbtq_total', '{ "type": "integer" }' ),
('Organization Board African Descent' , 'organization_board_african_descent', '{ "type": "integer" }' ),
('Organization Board Asian Descent' , 'organization_board_asian_descent', '{ "type": "integer" }' ),
('Organization Board European Descent' , 'organization_board_european_descent', '{ "type": "integer" }' ),
('Organization Board Indigenous Peoples' , 'organization_board_indigenous_peoples', '{ "type": "integer" }' ),
('Organization Board Latin American Descent' , 'organization_board_latin_american_descent', '{ "type": "integer" }' ),
('Organization Board Middle Eastern Descent' , 'organization_board_middle_eastern_descent', '{ "type": "integer" }' ),
('Organization Board Multiracial Descent' , 'organization_board_multiracial_descent', '{ "type": "integer" }' ),
('Organization Paid Staff' , 'organization_paid_staff', '{ "type": "integer" }' ),
('Organization Senior Staff Women' , 'organization_senior_staff_women', '{ "type": "integer" }' ),
('Organization Senior Staff Young Women' , 'organization_senior_staff_young_women', '{ "type": "integer" }' ),
('Organization Senior Staff Older Women' , 'organization_senior_staff_older_women', '{ "type": "integer" }' ),
('Organization Senior Staff Senior Women' , 'organization_senior_staff_senior_women', '{ "type": "integer" }' ),
('Organization Senior Staff Women - Total' , 'organization_senior_staff_women_total', '{ "type": "integer" }' ),
('Organization Senior Staff Men - Men' , 'organization_senior_staff_men_men', '{ "type": "integer" }' ),
('Organization Senior Staff Men - Young Men' , 'organization_senior_staff_men_young_men', '{ "type": "integer" }' ),
('Organization Senior Staff Men - Older Men' , 'organization_senior_staff_men_older_men', '{ "type": "integer" }' ),
('Organization Senior Staff Men - Senior Men' , 'organization_senior_staff_men_senior_men', '{ "type": "integer" }' ),
('Organization Senior Staff Men - Total' , 'organization_senior_staff_men_total', '{ "type": "integer" }' ),
('Organization Senior Staff Intersex People' , 'organization_senior_staff_intersex_people', '{ "type": "integer" }' ),
('Organization Senior Staff Heterosexuals' , 'organization_senior_staff_heterosexuals', '{ "type": "integer" }' ),
('Organization Senior Staff LGBTQ Lesbians' , 'organization_senior_staff_lgbtq_lesbians', '{ "type": "integer" }' ),
('Organization Senior Staff LGBTQ Gay Men' , 'organization_senior_staff_lgbtq_gay_men', '{ "type": "integer" }' ),
('Organization Senior Staff LGBTQ Bisexuals' , 'organization_senior_staff_lgbtq_bisexuals', '{ "type": "integer" }' ),
('Organization Senior Staff LGBTQ Transgender' , 'organization_senior_staff_lgbtq_transgender', '{ "type": "integer" }' ),
('Organization Senior Staff LGBTQ - Total' , 'organization_senior_staff_lgbtq_total', '{ "type": "integer" }' ),
('Organization Senior Staff African Descent' , 'organization_senior_staff_african_descent', '{ "type": "integer" }' ),
('Organization Senior Staff Asian Descent' , 'organization_senior_staff_asian_descent', '{ "type": "integer" }' ),
('Organization Senior Staff European Descent' , 'organization_senior_staff_european_descent', '{ "type": "integer" }' ),
('Organization Senior Staff Indigenous Peoples' , 'organization_senior_staff_indigenous_peoples', '{ "type": "integer" }' ),
('Organization Senior Staff Latin American Descent' , 'organization_senior_staff_latin_american_descent', '{ "type": "integer" }' ),
('Organization Senior Staff Middle Eastern Descent' , 'organization_senior_staff_middle_eastern_descent', '{ "type": "integer" }' ),
('Organization Senior Staff Multiracial Descent' , 'organization_senior_staff_multiracial_descent', '{ "type": "integer" }' ),
('Organization Conflict of Interest Policy' , 'organization_conflict_of_interest_policy', '{ "type": "string" }' ),
('Organization Workplace Issues' , 'organization_workplace_issues', '{ "type": "string" }' ),
('Organization Whistleblower Policy' , 'organization_whistleblower_policy', '{ "type": "string" }' ),
('Organization Financial Statements' , 'organization_financial_statements', '{ "type": "string" }' ),
('Organization Legal Documents' , 'organization_legal_documents', '{ "type": "string" }' ),
('Proposal Date' , 'proposal_date', '{ "type": "string", "format": "date-time" }' ),
('Proposal Name' , 'proposal_name', '{ "type": "string" }' ),
('Proposal Title' , 'proposal_title', '{ "type": "string" }' ),
('Proposal Type' , 'proposal_type', '{ "type": "string" }' ),
('Proposal Focus' , 'proposal_focus', '{ "type": "string" }' ),
('Proposal Summary' , 'proposal_summary', '{ "type": "string" }' ),
('Proposal Primary Contact Name' , 'proposal_primary_contact_name', '{ "type": "string" }' ),
('Proposal Primary Contact Title' , 'proposal_primary_contact_title', '{ "type": "string" }' ),
('Proposal Primary Contact Phone' , 'proposal_primary_contact_phone', '{ "type": "string" }' ),
('Proposal Primary Contact Email' , 'proposal_primary_contact_email', '{ "type": "string" }' ),
('Proposal Submitter Prefix' , 'proposal_submitter_prefix', '{ "type": "string" }' ),
('Proposal Submitter First Name' , 'proposal_submitter_first_name', '{ "type": "string" }' ),
('Proposal Submitter Middle Initial' , 'proposal_submitter_middle_initial', '{ "type": "string" }' ),
('Proposal Submitter Last Name' , 'proposal_submitter_last_name', '{ "type": "string" }' ),
('Proposal Submitter Suffix' , 'proposal_submitter_suffix', '{ "type": "string" }' ),
('Proposal Submitter Title' , 'proposal_submitter_title', '{ "type": "string" }' ),
('Proposal Submitter Phone' , 'proposal_submitter_phone', '{ "type": "string" }' ),
('Proposal Submitter Extension' , 'proposal_submitter_extension', '{ "type": "string" }' ),
('Proposal Submitter Mobile Phone' , 'proposal_submitter_mobile_phone', '{ "type": "string" }' ),
('Proposal Submitter Email' , 'proposal_submitter_email', '{ "type": "string" }' ),
('Proposal Submitter Street Address 1' , 'proposal_submitter_street_address_1', '{ "type": "string" }' ),
('Proposal Submitter Street Address 2' , 'proposal_submitter_street_address_2', '{ "type": "string" }' ),
('Proposal Submitter City/Town' , 'proposal_submitter_city_town', '{ "type": "string" }' ),
('Proposal Submitter State/Province' , 'proposal_submitter_state_province', '{ "type": "string" }' ),
('Proposal Submitter State Code' , 'proposal_submitter_state_code', '{ "type": "string" }' ),
('Proposal Submitter Region' , 'proposal_submitter_region', '{ "type": "string" }' ),
('Proposal Submitter Zip Code' , 'proposal_submitter_zip_code', '{ "type": "string" }' ),
('Proposal Submitter Name' , 'proposal_submitter_name', '{ "type": "string" }' ),
('Proposal Amount Requested' , 'proposal_amount_requested', '{ "type": "number" }' ),
('Proposal Funding Category' , 'proposal_funding_category', '{ "type": "string" }' ),
('Proposal Budget' , 'proposal_budget', '{ "type": "number" }' ),
('Proposal Budget Narrative' , 'proposal_budget_narrative', '{ "type": "string" }' ),
('Proposal Project Budget' , 'proposal_project_budget', '{ "type": "number" }' ),
('Proposal Fiscal Sponsor?' , 'proposal_fiscal_sponsor', '{ "type": "boolean" }' ),
('Proposal Fiscal Sponsor Information' , 'proposal_fiscal_sponsor_information', '{ "type": "string" }' ),
('Proposal Fiscal Sponsor Name' , 'proposal_fiscal_sponsor_name', '{ "type": "string" }' ),
('Proposal Fiscal Sponsor EIN' , 'proposal_fiscal_sponsor_ein', '{ "type": "string" }' ),
('Proposal Fiscal Sponsor Contact First Name' , 'proposal_fiscal_sponsor_contact_first_name', '{ "type": "string" }' ),
('Proposal Fiscal Sponsor Cantact Last Name' , 'proposal_fiscal_sponsor_cantact_last_name', '{ "type": "string" }' ),
('Proposal Fiscal Sponsor Contact Email' , 'proposal_fiscal_sponsor_contact_email', '{ "type": "string" }' ),
('Proposal Regrant' , 'proposal_regrant', '{ "type": "string" }' ),
('Proposal Regrant Subgrantees' , 'proposal_regrant_subgrantees', '{ "type": "string" }' ),
('Proposal Subgrantee List' , 'proposal_subgrantee_list', '{ "type": "string" }' ),
('Proposal Expenditure Responsibility' , 'proposal_expenditure_responsibility', '{ "type": "string" }' ),
('Proposal Equivalency Determination' , 'proposal_equivalency_determination', '{ "type": "string" }' ),
('Proposal Tipping Amount' , 'proposal_tipping_amount', '{ "type": "number" }' ),
('Proposal Funding Summary' , 'proposal_funding_summary', '{ "type": "string" }' ),
('Proposal Start Date' , 'proposal_start_date', '{ "type": "string", "format": "date-time" }' ),
('Proposal End Date' , 'proposal_end_date', '{ "type": "string", "format": "date-time" }' ),
('Proposal Duration' , 'proposal_duration', '{ "type": "string" }' ),
('Proposal Location of Work' , 'proposal_location_of_work', '{ "type": "string" }' ),
('Proposal Age Group' , 'proposal_age_group', '{ "type": "string" }' ),
('Proposal Ethnicity' , 'proposal_ethnicity', '{ "type": "string" }' ),
('Proposal Need' , 'proposal_need', '{ "type": "string" }' ),
('Proposal Activities' , 'proposal_activities', '{ "type": "string" }' ),
('Proposal Tactics and Methods' , 'proposal_tactics_and_methods', '{ "type": "string" }' ),
('Proposal Strategy' , 'proposal_strategy', '{ "type": "string" }' ),
('Proposal Organizational Strengths' , 'proposal_organizational_strengths', '{ "type": "string" }' ),
('Proposal Equity' , 'proposal_equity', '{ "type": "string" }' ),
('Proposal Engagement' , 'proposal_engagement', '{ "type": "string" }' ),
('Proposal Challenges and Risks' , 'proposal_challenges_and_risks', '{ "type": "string" }' ),
('Proposal Related Programs' , 'proposal_related_programs', '{ "type": "string" }' ),
('Proposal Supplemental Information' , 'proposal_supplemental_information', '{ "type": "string" }' ),
('Proposal Results' , 'proposal_results', '{ "type": "string" }' ),
('Proposal Project Outcomes' , 'proposal_project_outcomes', '{ "type": "string" }' ),
('Proposal Anticipated Impact' , 'proposal_anticipated_impact', '{ "type": "string" }' ),
('Proposal Sustainability' , 'proposal_sustainability', '{ "type": "string" }' ),
('Proposal IRB Approval Needed' , 'proposal_irb_approval_needed', '{ "type": "string" }' ),
('Proposal IRB Approval Obtained' , 'proposal_irb_approval_obtained', '{ "type": "string" }' ),
('Organization Lobbying Activities' , 'organization_lobbying_activities', '{ "type": "string" }' ),
('Proposal Legislation' , 'proposal_legislation', '{ "type": "string" }' ),
('Proposal Lobbying more than Grant' , 'proposal_lobbying_more_than_grant', '{ "type": "boolean" }' ),
('Review Amount Recommended' , 'review_amount_recommended', '{ "type": "string" }' ),
('Review Comments to Applicant' , 'review_comments_to_applicant', '{ "type": "string" }' ),
('Review Additional Comments' , 'review_additional_comments', '{ "type": "string" }' ),
('Review Grant Agreement Date' , 'review_grant_agreement_date', '{ "type": "string", "format": "date-time" }' ),
('Review Start Date' , 'review_start_date', '{ "type": "string", "format": "date-time" }' ),
('Review End Date' , 'review_end_date', '{ "type": "string", "format": "date-time" }' ),
('Review Close Date' , 'review_close_date', '{ "type": "string", "format": "date-time" }' ),
('Review  Submission ID' , 'review_submission_id', '{ "type": "integer" }' ),
('Review Status' , 'review_status', '{ "type": "string" }' ),
('Review Date' , 'review_date', '{ "type": "string", "format": "date-time" }' ),
('Review Submission URL' , 'review_submission_url', '{ "type": "string" }' ),
('Review Labels' , 'review_labels', '{ "type": "string" }' ),
('Review Affiliate ID' , 'review_affiliate_id', '{ "type": "integer" }' ),
('Review Assigned To' , 'review_assigned_to', '{ "type": "string" }' ),
('Review Current Review Stage' , 'review_current_review_stage', '{ "type": "string" }' ),
('Review Total Score' , 'review_total_score', '{ "type": "integer" }' ),
('Review Average Score' , 'review_average_score', '{ "type": "integer" }' ),
('Review Gallery Votes' , 'review_gallery_votes', '{ "type": "integer" }' ),
('Review Total Votes' , 'review_total_votes', '{ "type": "integer" }' ),
('PDC Share Data' , 'pdc_share_data', '{ "type": "string" }' ),
('What is the overall CC score (could have decmials)' , 'what_is_the_overall_cc_score', '{ "type": "number" }' ),
('Rounded CC score to remove decimals' , 'rounded_cc_score_to_remove_decimals', '{ "type": "integer" }' ),
('Date Record was created' , 'date_record_was_created', '{ "type": "string", "format": "date-time" }' ),
('Date Record was published' , 'date_record_was_published', '{ "type": "string", "format": "date-time" }' ),
('End date for the time period covered by this tax form for the rated fiscal year' , 'end_date_for_the_time_period_covered_by_this_tax_form_for_the_rated_fiscal_year', '{ "type": "string", "format": "date-time" }' ),
('Did they pass Board Size Metric' , 'did_they_pass_board_size_metric', '{ "type": "boolean" }' ),
('Did they pass Board Ratio Metric' , 'did_they_pass_board_ratio_metric', '{ "type": "boolean" }' ),
('Did they pass URL on 990 Metric' , 'did_they_pass_url_on_990_metric', '{ "type": "boolean" }' ),
('Did they pass board minutes Metric' , 'did_they_pass_board_minutes_metric', '{ "type": "boolean" }' ),
('Did they pass whistleblower Metric' , 'did_they_pass_whistleblower_metric', '{ "type": "boolean" }' ),
('Did they pass conflict of interest Metric' , 'did_they_pass_conflict_of_interest_metric', '{ "type": "boolean" }' ),
('Did they pass Document Retention Metric' , 'did_they_pass_document_retention_metric', '{ "type": "boolean" }' ),
('Did they pass Audit/Review Metric' , 'did_they_pass_audit_review_metric', '{ "type": "boolean" }' ),
('Rounded Total Score for FA' , 'rounded_total_score_for_fa', '{ "type": "integer" }' ),
('Do they have an audit' , 'do_they_have_an_audit', '{ "type": "boolean" }' ),
('Do they have board minutes' , 'do_they_have_board_minutes', '{ "type": "boolean" }' ),
('Do they have a whistleblower policy' , 'do_they_have_a_whistleblower_policy', '{ "type": "boolean" }' ),
('Do they have a compliation or review' , 'do_they_have_a_compliation_or_review', '{ "type": "boolean" }' ),
('Do they have a conflict of interest policy' , 'do_they_have_a_conflict_of_interest_policy', '{ "type": "boolean" }' ),
('Do they have a document retention policy' , 'do_they_have_a_document_retention_policy', '{ "type": "boolean" }' ),
('Is their URL listed on the 990' , 'is_their_url_listed_on_the_990', '{ "type": "boolean" }' ),
('What is the percent of their independant board' , 'what_is_the_percent_of_their_independant_board', '{ "type": "number" }' ),
('Rating year' , 'rating_year', '{ "type": "string" }' ),
('Date F&A beacon published' , 'date_f&a_beacon_published', '{ "type": "string", "format": "date-time" }' ),
('Total Finace score' , 'total_finace_score', '{ "type": "integer" }' ),
('Total Accountability Score' , 'total_accountability_score', '{ "type": "integer" }' ),
('Impact and Results Score' , 'impact_and_results_score', '{ "type": "integer" }' ),
('Cost per outcome statement' , 'cost_per_outcome_statement', '{ "type": "integer" }' ),
('If it is cost-effective, highly cost-effective or not cost effective' , 'if_it_is_cost_effective_highly_cost_effective_or_not_cost_effective', '{ "type": "string" }' ),
('Program categories' , 'program_categories', '{ "type": "string" }' ),
('summary of the activities' , 'summary_of_the_activities', '{ "type": "string" }' ),
('Who they serve' , 'who_they_serve', '{ "type": "string" }' ),
('Data time period' , 'data_time_period_', '{ "type": "string" }' ),
('Outcome metric measures' , 'outcome_metric_measures', '{ "type": "string" }' ),
('How they calculated counterfactual' , 'how_they_calculated_counterfactual_', '{ "type": "string" }' ),
('data source for calculation' , 'data_source_for_calculation', '{ "type": "string" }' ),
('the arithmetic for the cost calculation' , 'the_arithmetic_for_the_cost_calculation', '{ "type": "string" }' ),
('Impact calcuation.' , 'impact_calcuation', '{ "type": "string" }' ),
('Benchmark for comparision' , 'benchmark_for_comparision', '{ "type": "string" }' ),
('Date impact rating was created' , 'date_impact_rating_was_created', '{ "type": "string" }' ),
('Score for mission statement' , 'score_for_mission_statement', '{ "type": "integer" }' ),
('Score for vision statement' , 'score_for_vision_statement', '{ "type": "integer" }' ),
('Score for goals score' , 'score_for_goals_score', '{ "type": "integer" }' ),
('Overall Strategy score' , 'overall_strategy_score', '{ "type": "integer" }' ),
('Leadership metrics investment_score' , 'leadership_metrics_investment_score', '{ "type": "integer" }' ),
('Leadership metrics external focus_score' , 'leadership_metrics_external_focus_score', '{ "type": "integer" }' ),
('Overal leadership score' , 'overal_leadership_score', '{ "type": "integer" }' ),
('Adaptablity metrics- Score' , 'adaptablity_metrics_score', '{ "type": "integer" }' ),
('Overall adaptablity score' , 'overall_adaptablity_score', '{ "type": "integer" }' ),
('Total Leadership and Adaptablity score' , 'total_leadership_and_adaptablity_score', '{ "type": "integer" }' ),
('Created L&A score date' , 'created_l&a_score_date', '{ "type": "string", "format": "date-time" }' ),
('Is this an overall Encompass passing rating' , 'is_this_an_overall_encompass_passing_rating', '{ "type": "boolean" }' ),
('Is this rating eligible for publishing' , 'is_this_rating_eligible_for_publishing', '{ "type": "boolean" }' ),
('Overall Encompass Score (including decimals)' , 'overall_encompass_score_decimal', '{ "type": "number" }' ),
('Overall Encompass Score (rounded to whole numbers)' , 'overall_encompass_score_rounded', '{ "type": "integer" }' ),
('Total points avaiable in Encompass' , 'total_points_avaiable_in_encompass', '{ "type": "integer" }' ),
('When was this Overall Rating created' , 'when_was_this_overall_rating_created', '{ "type": "string", "format": "date-time" }' ),
('Category of Charity (Highest level of cause categorization)' , 'category_of_charity', '{ "type": "string" }' ),
('Cause of Charity (Mid Level of cause categorization)' , 'cause_of_charity', '{ "type": "string" }' ),
('Date of latest source' , 'date_of_latest_source', '{ "type": "string", "format": "date-time" }' ),
('Is there a donor advisory on this charity?' , 'is_there_a_donor_advisory_on_this_charity', '{ "type": "boolean" }' ),
('Text of the donor advisory message in html' , 'text_of_the_donor_advisory_message_in_html', '{ "type": "string" }' ),
('Date the donor advisory went live' , 'date_the_donor_advisory_went_live', '{ "type": "string", "format": "date-time" }' ),
('Date Current CEO was last verified' , 'date_current_ceo_was_last_verified', '{ "type": "string", "format": "date-time" }' ),
('Web location of pro-forma 990s to handle Pharmaceutical valuation adjustments' , 'web_location_of_proforma_990s_to_handle_pharmaceutical_valuation_adjustments', '{ "type": "string" }' ),
('Fiscal Year of Financial Rating' , 'fiscal_year_of_financial_rating', '{ "type": "string" }' ),
('Fundraising Efficiency Amount' , 'fundraising_efficiency_amount', '{ "type": "integer" }' ),
('Fundraising Expense Ratio' , 'fundraising_expense_ratio', '{ "type": "string" }' ),
('Program Expense Ratio' , 'program_expense_ratio', '{ "type": "string" }' ),
('Administrative Expense Ratio' , 'administrative_expense_ratio', '{ "type": "string" }' ),
('Working Capital Ratio' , 'working_capital_ratio', '{ "type": "string" }' ),
('Fundraising Efficiency Score' , 'fundraising_efficiency_score', '{ "type": "integer" }' ),
('Fundraising Expense Score' , 'fundraising_expense_score', '{ "type": "integer" }' ),
('Program Expense Score' , 'program_expense_score', '{ "type": "integer" }' ),
('Administrative Expense Score' , 'administrative_expense_score', '{ "type": "integer" }' ),
('Primary Revenue Growth Score' , 'primary_revenue_growth_score', '{ "type": "integer" }' ),
('Program Expense Growth Score' , 'program_expense_growth_score', '{ "type": "integer" }' ),
('Working Capital Score' , 'working_capital_score', '{ "type": "integer" }' ),
('Score in the Financial dimension' , 'score_in_the_financial_dimension', '{ "type": "integer" }' ),
('Score in the A&T dimension' , 'score_in_the_a&t_dimension', '{ "type": "integer" }' ),
('Rating in the A&T dimension' , 'rating_in_the_a&t_dimension', '{ "type": "integer" }' ),
('Score in the Results dimension' , 'score_in_the_results_dimension', '{ "type": "integer" }' ),
('Rating in the Results Dimension' , 'rating_in_the_results_dimension', '{ "type": "integer" }' ),
('Overall Score' , 'overall_score', '{ "type": "integer" }' ),
('Overall Rating' , 'overall_rating', '{ "type": "integer" }' ),
('Yes/No indicator: This rating is a Donor Advisory' , 'yes_no_indicator_this_rating_is_a_donor_advisory', '{ "type": "boolean" }' );
