-- Use the included INSERT statement to seed base fields data.

-- This script helps get a development database started with some base fields.

-- Usage example 1: `psql -d pdc -U pdc -p 5432 -f 0001-insert-base_fields.sql`
-- Usage example 2: `cat 0001-insert-base_fields.sql` then copy/paste into a `psql` session.

-- If you get a `violates unique constraint` error, you might already have run the script once.
-- If you get the `violates unique constraint` error and didn't run it, you have a conflicting row
-- in your database instance in the base_fields table. The error `DETAIL` should help you find
-- the problem row. Try `DELETE FROM base_fields WHERE short_code='the_short_code'` to remove
-- the existing row. If such a `DELETE` fails due to a foreign key reference, that means the
-- base field is already used in an application form and should probably not be removed unless
-- you are OK with first removing the application form and its dependent data in proposals,
-- proposal versions, and proposal field values.

-- The SQL in this file was generated from a spreadsheet as input to a script here:
-- https://github.com/PhilanthropyDataCommons/data-scripts/commit/2af7a7109017f7d43ff7593660dbdce44732d126

INSERT INTO base_fields (label, description, short_code, data_type) VALUES
('Organization Name', '', 'organization_name', 'string' ),
('Organization Legal Name' , '', 'organization_legal_name', 'string' ),
('Organization DBA Name' , '', 'organization_dba_name', 'string' ),
('Organization Acronym' , '', 'organization_acronym', 'string' ),
('Organization ID' , '', 'organization_id', 'string' ),
('Organization Charitable Organization' , '', 'organization_charitable_organization', 'string' ),
('Organization Entity Type' , '', 'organization_entity_type', 'string' ),
('Organization Tax ID' , '', 'organization_tax_id', 'string' ),
('Organization Tax Status Date' , '', 'organization_tax_status_date', 'string' ),
('Organization Street Address 1' , '', 'organization_street_address_1', 'string' ),
('Organization Street Address 2' , '', 'organization_street_address_2', 'string' ),
('Organization City' , '', 'organization_city', 'string' ),
('Organization County' , '', 'organization_county', 'string' ),
('Organization State/Province' , '', 'organization_state_province', 'string' ),
('Organization Region' , '', 'organization_region', 'string' ),
('Organization Country' , '', 'organization_country', 'string' ),
('Organization Postal Code' , '', 'organization_postal_code', 'number' ),
('Organization Phone' , '', 'organization_phone', 'phone_number' ),
('Organization Email' , '', 'organization_email', 'string' ),
('Organization Website' , '', 'organization_website', 'string' ),
('Organization Mission Statement' , '', 'organization_mission_statement', 'string' ),
('Organization Start Date' , '', 'organization_start_date', 'string' ),
('Organization Fiscal Year End Date' , '', 'organization_fiscal_year_end_date', 'string' ),
('Organization Fiscal Year End Date - Month' , '', 'organization_fiscal_year_end_date_month', 'string' ),
('Organization Fiscal Year End Date - Year' , '', 'organization_fiscal_year_end_date_year', 'string' ),
('Organization Operating Budget' , '', 'organization_operating_budget', 'number' ),
('Organization Geographic Area' , '', 'organization_geographic_area', 'string' ),
('Organization Executive/Administrator' , '', 'organization_executive_administrator', 'string' ),
('Organization Executive/Administrator Title' , '', 'organization_executive_administrator_title', 'string' ),
('Organization Executive/Administrator Race' , '', 'organization_executive_administrator_race', 'string' ),
('Organization Executive/Administrator Gender' , '', 'organization_executive_administrator_gender', 'string' ),
('Organization Executive/Administrator Sexual Orientation' , '', 'organization_executive_administrator_sexual_orientation', 'string' ),
('Organization Executive/Administrator Disability Status' , '', 'organization_executive_administrator_disability_status', 'string' ),
('CEO Review Method' , '', 'ceo_review_method', 'string' ),
('Organization Signatory' , '', 'organization_signatory', 'string' ),
('Organization Financial Officer' , '', 'organization_financial_officer', 'string' ),
('Organization Grants Officer' , '', 'organization_grants_officer', 'string' ),
('Organization Banking Contact' , '', 'organization_banking_contact', 'string' ),
('Organization Leadership' , '', 'organization_leadership', 'string' ),
('Organization Governing Body Type' , '', 'organization_governing_body_type', 'string' ),
('Organization Governing Body Term Duration' , '', 'organization_governing_body_term_duration', 'string' ),
('Organization Governing Body Number of Terms Permitted' , '', 'organization_governing_body_number_of_terms_permitted', 'string' ),
('Organization Governing Body Compensation' , '', 'organization_governing_body_compensation', 'string' ),
('Organization Governing Body Financial Oversight' , '', 'organization_governing_body_financial_oversight', 'string' ),
('Organization Board Chair' , '', 'organization_board_chair', 'string' ),
('Organization Board Chair Title' , '', 'organization_board_chair_title', 'string' ),
('Organization Board Members' , '', 'organization_board_members', 'number' ),
('Organization Board Women' , '', 'organization_board_women', 'number' ),
('Organization Board Young Women' , '', 'organization_board_young_women', 'number' ),
('Organization Board Older Women' , '', 'organization_board_older_women', 'number' ),
('Organization Board Senior Women' , '', 'organization_board_senior_women', 'number' ),
('Organization Board Women - Total' , '', 'organization_board_women_total', 'number' ),
('Organization Board Men' , '', 'organization_board_men', 'number' ),
('Organization Board Young Men' , '', 'organization_board_young_men', 'number' ),
('Organization Board Older Men' , '', 'organization_board_older_men', 'number' ),
('Organization Board Senior Men' , '', 'organization_board_senior_men', 'number' ),
('Organization Board Men - Total' , '', 'organization_board_men_total', 'number' ),
('Organization Board Intersex' , '', 'organization_board_intersex', 'number' ),
('Organization Board Heterosexuals' , '', 'organization_board_heterosexuals', 'number' ),
('Organization Board LGBTQ Lesbians' , '', 'organization_board_lgbtq_lesbians', 'number' ),
('Organization Board LGBTQ Gay Men' , '', 'organization_board_lgbtq_gay_men', 'number' ),
('Organization Board LGBTQ Bisexuals' , '', 'organization_board_lgbtq_bisexuals', 'number' ),
('Organization Board LGBTQ Transgender' , '', 'organization_board_lgbtq_transgender', 'number' ),
('Organization Board LGBTQ - Total' , '', 'organization_board_lgbtq_total', 'number' ),
('Organization Board African Descent' , '', 'organization_board_african_descent', 'number' ),
('Organization Board Asian Descent' , '', 'organization_board_asian_descent', 'number' ),
('Organization Board European Descent' , '', 'organization_board_european_descent', 'number' ),
('Organization Board Indigenous Peoples' , '', 'organization_board_indigenous_peoples', 'number' ),
('Organization Board Latin American Descent' , '', 'organization_board_latin_american_descent', 'number' ),
('Organization Board Middle Eastern Descent' , '', 'organization_board_middle_eastern_descent', 'number' ),
('Organization Board Multiracial Descent' , '', 'organization_board_multiracial_descent', 'number' ),
('Organization Paid Staff' , '', 'organization_paid_staff', 'number' ),
('Organization Senior Staff Women' , '', 'organization_senior_staff_women', 'number' ),
('Organization Senior Staff Young Women' , '', 'organization_senior_staff_young_women', 'number' ),
('Organization Senior Staff Older Women' , '', 'organization_senior_staff_older_women', 'number' ),
('Organization Senior Staff Senior Women' , '', 'organization_senior_staff_senior_women', 'number' ),
('Organization Senior Staff Women - Total' , '', 'organization_senior_staff_women_total', 'number' ),
('Organization Senior Staff Men - Men' , '', 'organization_senior_staff_men_men', 'number' ),
('Organization Senior Staff Men - Young Men' , '', 'organization_senior_staff_men_young_men', 'number' ),
('Organization Senior Staff Men - Older Men' , '', 'organization_senior_staff_men_older_men', 'number' ),
('Organization Senior Staff Men - Senior Men' , '', 'organization_senior_staff_men_senior_men', 'number' ),
('Organization Senior Staff Men - Total' , '', 'organization_senior_staff_men_total', 'number' ),
('Organization Senior Staff Intersex People' , '', 'organization_senior_staff_intersex_people', 'number' ),
('Organization Senior Staff Heterosexuals' , '', 'organization_senior_staff_heterosexuals', 'number' ),
('Organization Senior Staff LGBTQ Lesbians' , '', 'organization_senior_staff_lgbtq_lesbians', 'number' ),
('Organization Senior Staff LGBTQ Gay Men' , '', 'organization_senior_staff_lgbtq_gay_men', 'number' ),
('Organization Senior Staff LGBTQ Bisexuals' , '', 'organization_senior_staff_lgbtq_bisexuals', 'number' ),
('Organization Senior Staff LGBTQ Transgender' , '', 'organization_senior_staff_lgbtq_transgender', 'number' ),
('Organization Senior Staff LGBTQ - Total' , '', 'organization_senior_staff_lgbtq_total', 'number' ),
('Organization Senior Staff African Descent' , '', 'organization_senior_staff_african_descent', 'number' ),
('Organization Senior Staff Asian Descent' , '', 'organization_senior_staff_asian_descent', 'number' ),
('Organization Senior Staff European Descent' , '', 'organization_senior_staff_european_descent', 'number' ),
('Organization Senior Staff Indigenous Peoples' , '', 'organization_senior_staff_indigenous_peoples', 'number' ),
('Organization Senior Staff Latin American Descent' , '', 'organization_senior_staff_latin_american_descent', 'number' ),
('Organization Senior Staff Middle Eastern Descent' , '', 'organization_senior_staff_middle_eastern_descent', 'number' ),
('Organization Senior Staff Multiracial Descent' , '', 'organization_senior_staff_multiracial_descent', 'number' ),
('Organization Conflict of Interest Policy' , '', 'organization_conflict_of_interest_policy', 'string' ),
('Organization Workplace Issues' , '', 'organization_workplace_issues', 'string' ),
('Organization Whistleblower Policy' , '', 'organization_whistleblower_policy', 'string' ),
('Organization Financial Statements' , '', 'organization_financial_statements', 'string' ),
('Organization Legal Documents' , '', 'organization_legal_documents', 'string' ),
('Proposal Date' , '', 'proposal_date', 'string' ),
('Proposal Name' , '', 'proposal_name', 'string' ),
('Proposal Title' , '', 'proposal_title', 'string' ),
('Proposal Type' , '', 'proposal_type', 'string' ),
('Proposal Focus' , '', 'proposal_focus', 'string' ),
('Proposal Summary' , '', 'proposal_summary', 'string' ),
('Proposal Primary Contact Name' , '', 'proposal_primary_contact_name', 'string' ),
('Proposal Primary Contact Title' , '', 'proposal_primary_contact_title', 'string' ),
('Proposal Primary Contact Phone' , '', 'proposal_primary_contact_phone', 'phone_number' ),
('Proposal Primary Contact Email' , '', 'proposal_primary_contact_email', 'string' ),
('Proposal Submitter Prefix' , '', 'proposal_submitter_prefix', 'string' ),
('Proposal Submitter First Name' , '', 'proposal_submitter_first_name', 'string' ),
('Proposal Submitter Middle Initial' , '', 'proposal_submitter_middle_initial', 'string' ),
('Proposal Submitter Last Name' , '', 'proposal_submitter_last_name', 'string' ),
('Proposal Submitter Suffix' , '', 'proposal_submitter_suffix', 'string' ),
('Proposal Submitter Title' , '', 'proposal_submitter_title', 'string' ),
('Proposal Submitter Phone' , '', 'proposal_submitter_phone', 'phone_number' ),
('Proposal Submitter Extension' , '', 'proposal_submitter_extension', 'string' ),
('Proposal Submitter Mobile Phone' , '', 'proposal_submitter_mobile_phone', 'phone_number' ),
('Proposal Submitter Email' , '', 'proposal_submitter_email', 'string' ),
('Proposal Submitter Street Address 1' , '', 'proposal_submitter_street_address_1', 'string' ),
('Proposal Submitter Street Address 2' , '', 'proposal_submitter_street_address_2', 'string' ),
('Proposal Submitter City/Town' , '', 'proposal_submitter_city_town', 'string' ),
('Proposal Submitter State/Province' , '', 'proposal_submitter_state_province', 'string' ),
('Proposal Submitter State Code' , '', 'proposal_submitter_state_code', 'string' ),
('Proposal Submitter Region' , '', 'proposal_submitter_region', 'string' ),
('Proposal Submitter Zip Code' , '', 'proposal_submitter_zip_code', 'string' ),
('Proposal Submitter Name' , '', 'proposal_submitter_name', 'string' ),
('Proposal Amount Requested' , '', 'proposal_amount_requested', 'number' ),
('Proposal Funding Category' , '', 'proposal_funding_category', 'string' ),
('Proposal Budget' , '', 'proposal_budget', 'number' ),
('Proposal Budget Narrative' , '', 'proposal_budget_narrative', 'string' ),
('Proposal Project Budget' , '', 'proposal_project_budget', 'number' ),
('Proposal Fiscal Sponsor?' , '', 'proposal_fiscal_sponsor', 'boolean' ),
('Proposal Fiscal Sponsor Information' , '', 'proposal_fiscal_sponsor_information', 'string' ),
('Proposal Fiscal Sponsor Name' , '', 'proposal_fiscal_sponsor_name', 'string' ),
('Proposal Fiscal Sponsor EIN' , '', 'proposal_fiscal_sponsor_ein', 'string' ),
('Proposal Fiscal Sponsor Contact First Name' , '', 'proposal_fiscal_sponsor_contact_first_name', 'string' ),
('Proposal Fiscal Sponsor Cantact Last Name' , '', 'proposal_fiscal_sponsor_cantact_last_name', 'string' ),
('Proposal Fiscal Sponsor Contact Email' , '', 'proposal_fiscal_sponsor_contact_email', 'string' ),
('Proposal Regrant' , '', 'proposal_regrant', 'string' ),
('Proposal Regrant Subgrantees' , '', 'proposal_regrant_subgrantees', 'string' ),
('Proposal Subgrantee List' , '', 'proposal_subgrantee_list', 'string' ),
('Proposal Expenditure Responsibility' , '', 'proposal_expenditure_responsibility', 'string' ),
('Proposal Equivalency Determination' , '', 'proposal_equivalency_determination', 'string' ),
('Proposal Tipping Amount' , '', 'proposal_tipping_amount', 'number' ),
('Proposal Funding Summary' , '', 'proposal_funding_summary', 'string' ),
('Proposal Start Date' , '', 'proposal_start_date', 'string' ),
('Proposal End Date' , '', 'proposal_end_date', 'string' ),
('Proposal Duration' , '', 'proposal_duration', 'string' ),
('Proposal Location of Work' , '', 'proposal_location_of_work', 'string' ),
('Proposal Age Group' , '', 'proposal_age_group', 'string' ),
('Proposal Ethnicity' , '', 'proposal_ethnicity', 'string' ),
('Proposal Need' , '', 'proposal_need', 'string' ),
('Proposal Activities' , '', 'proposal_activities', 'string' ),
('Proposal Tactics and Methods' , '', 'proposal_tactics_and_methods', 'string' ),
('Proposal Strategy' , '', 'proposal_strategy', 'string' ),
('Proposal Organizational Strengths' , '', 'proposal_organizational_strengths', 'string' ),
('Proposal Equity' , '', 'proposal_equity', 'string' ),
('Proposal Engagement' , '', 'proposal_engagement', 'string' ),
('Proposal Challenges and Risks' , '', 'proposal_challenges_and_risks', 'string' ),
('Proposal Related Programs' , '', 'proposal_related_programs', 'string' ),
('Proposal Supplemental Information' , '', 'proposal_supplemental_information', 'string' ),
('Proposal Results' , '', 'proposal_results', 'string' ),
('Proposal Project Outcomes' , '', 'proposal_project_outcomes', 'string' ),
('Proposal Anticipated Impact' , '', 'proposal_anticipated_impact', 'string' ),
('Proposal Sustainability' , '', 'proposal_sustainability', 'string' ),
('Proposal IRB Approval Needed' , '', 'proposal_irb_approval_needed', 'string' ),
('Proposal IRB Approval Obtained' , '', 'proposal_irb_approval_obtained', 'string' ),
('Organization Lobbying Activities' , '', 'organization_lobbying_activities', 'string' ),
('Proposal Legislation' , '', 'proposal_legislation', 'string' ),
('Proposal Lobbying more than Grant' , '', 'proposal_lobbying_more_than_grant', 'boolean' ),
('Review Amount Recommended' , '', 'review_amount_recommended', 'string' ),
('Review Comments to Applicant' , '', 'review_comments_to_applicant', 'string' ),
('Review Additional Comments' , '', 'review_additional_comments', 'string' ),
('Review Grant Agreement Date' , '', 'review_grant_agreement_date', 'string' ),
('Review Start Date' , '', 'review_start_date', 'string' ),
('Review End Date' , '', 'review_end_date', 'string' ),
('Review Close Date' , '', 'review_close_date', 'string' ),
('Review  Submission ID' , '', 'review_submission_id', 'number' ),
('Review Status' , '', 'review_status', 'string' ),
('Review Date' , '', 'review_date', 'string' ),
('Review Submission URL' , '', 'review_submission_url', 'string' ),
('Review Labels' , '', 'review_labels', 'string' ),
('Review Affiliate ID' , '', 'review_affiliate_id', 'number' ),
('Review Assigned To' , '', 'review_assigned_to', 'string' ),
('Review Current Review Stage' , '', 'review_current_review_stage', 'string' ),
('Review Total Score' , '', 'review_total_score', 'number' ),
('Review Average Score' , '', 'review_average_score', 'number' ),
('Review Gallery Votes' , '', 'review_gallery_votes', 'number' ),
('Review Total Votes' , '', 'review_total_votes', 'number' ),
('PDC Share Data' , '', 'pdc_share_data', 'string' ),
('What is the overall CC score (could have decmials)' , '', 'what_is_the_overall_cc_score', 'number' ),
('Rounded CC score to remove decimals' , '', 'rounded_cc_score_to_remove_decimals', 'number' ),
('Date Record was created' , '', 'date_record_was_created', 'string' ),
('Date Record was published' , '', 'date_record_was_published', 'string' ),
('End date for the time period covered by this tax form for the rated fiscal year' , '', 'end_date_for_the_time_period_covered_by_this_tax_form_for_the_rated_fiscal_year', 'string' ),
('Did they pass Board Size Metric' , '', 'did_they_pass_board_size_metric', 'boolean' ),
('Did they pass Board Ratio Metric' , '', 'did_they_pass_board_ratio_metric', 'boolean' ),
('Did they pass URL on 990 Metric' , '', 'did_they_pass_url_on_990_metric', 'boolean' ),
('Did they pass board minutes Metric' , '', 'did_they_pass_board_minutes_metric', 'boolean' ),
('Did they pass whistleblower Metric' , '', 'did_they_pass_whistleblower_metric', 'boolean' ),
('Did they pass conflict of interest Metric' , '', 'did_they_pass_conflict_of_interest_metric', 'boolean' ),
('Did they pass Document Retention Metric' , '', 'did_they_pass_document_retention_metric', 'boolean' ),
('Did they pass Audit/Review Metric' , '', 'did_they_pass_audit_review_metric', 'boolean' ),
('Rounded Total Score for FA' , '', 'rounded_total_score_for_fa', 'number' ),
('Do they have an audit' , '', 'do_they_have_an_audit', 'boolean' ),
('Do they have board minutes' , '', 'do_they_have_board_minutes', 'boolean' ),
('Do they have a whistleblower policy' , '', 'do_they_have_a_whistleblower_policy', 'boolean' ),
('Do they have a compliation or review' , '', 'do_they_have_a_compliation_or_review', 'boolean' ),
('Do they have a conflict of interest policy' , '', 'do_they_have_a_conflict_of_interest_policy', 'boolean' ),
('Do they have a document retention policy' , '', 'do_they_have_a_document_retention_policy', 'boolean' ),
('Is their URL listed on the 990' , '', 'is_their_url_listed_on_the_990', 'boolean' ),
('What is the percent of their independant board' , '', 'what_is_the_percent_of_their_independant_board', 'number' ),
('Rating year' , '', 'rating_year', 'string' ),
('Date F&A beacon published' , '', 'date_f&a_beacon_published', 'string' ),
('Total Finace score' , '', 'total_finace_score', 'number' ),
('Total Accountability Score' , '', 'total_accountability_score', 'number' ),
('Impact and Results Score' , '', 'impact_and_results_score', 'number' ),
('Cost per outcome statement' , '', 'cost_per_outcome_statement', 'number' ),
('If it is cost-effective, highly cost-effective or not cost effective' , '', 'if_it_is_cost_effective_highly_cost_effective_or_not_cost_effective', 'string' ),
('Program categories' , '', 'program_categories', 'string' ),
('summary of the activities' , '', 'summary_of_the_activities', 'string' ),
('Who they serve' , '', 'who_they_serve', 'string' ),
('Data time period' , '', 'data_time_period_', 'string' ),
('Outcome metric measures' , '', 'outcome_metric_measures', 'string' ),
('How they calculated counterfactual' , '', 'how_they_calculated_counterfactual_', 'string' ),
('data source for calculation' , '', 'data_source_for_calculation', 'string' ),
('the arithmetic for the cost calculation' , '', 'the_arithmetic_for_the_cost_calculation', 'string' ),
('Impact calcuation.' , '', 'impact_calcuation', 'string' ),
('Benchmark for comparision' , '', 'benchmark_for_comparision', 'string' ),
('Date impact rating was created' , '', 'date_impact_rating_was_created', 'string' ),
('Score for mission statement' , '', 'score_for_mission_statement', 'number' ),
('Score for vision statement' , '', 'score_for_vision_statement', 'number' ),
('Score for goals score' , '', 'score_for_goals_score', 'number' ),
('Overall Strategy score' , '', 'overall_strategy_score', 'number' ),
('Leadership metrics investment_score' , '', 'leadership_metrics_investment_score', 'number' ),
('Leadership metrics external focus_score' , '', 'leadership_metrics_external_focus_score', 'number' ),
('Overal leadership score' , '', 'overal_leadership_score', 'number' ),
('Adaptablity metrics- Score' , '', 'adaptablity_metrics_score', 'number' ),
('Overall adaptablity score' , '', 'overall_adaptablity_score', 'number' ),
('Total Leadership and Adaptablity score' , '', 'total_leadership_and_adaptablity_score', 'number' ),
('Created L&A score date' , '', 'created_l&a_score_date', 'string' ),
('Is this an overall Encompass passing rating' , '', 'is_this_an_overall_encompass_passing_rating', 'boolean' ),
('Is this rating eligible for publishing' , '', 'is_this_rating_eligible_for_publishing', 'boolean' ),
('Overall Encompass Score (including decimals)' , '', 'overall_encompass_score_decimal', 'number' ),
('Overall Encompass Score (rounded to whole numbers)' , '', 'overall_encompass_score_rounded', 'number' ),
('Total points avaiable in Encompass' , '', 'total_points_avaiable_in_encompass', 'number' ),
('When was this Overall Rating created' , '', 'when_was_this_overall_rating_created', 'string' ),
('Category of Charity (Highest level of cause categorization)' , '', 'category_of_charity', 'string' ),
('Cause of Charity (Mid Level of cause categorization)' , '', 'cause_of_charity', 'string' ),
('Date of latest source' , '', 'date_of_latest_source', 'string' ),
('Is there a donor advisory on this charity?' , '', 'is_there_a_donor_advisory_on_this_charity', 'boolean' ),
('Text of the donor advisory message in html' , '', 'text_of_the_donor_advisory_message_in_html', 'string' ),
('Date the donor advisory went live' , '', 'date_the_donor_advisory_went_live', 'string' ),
('Date Current CEO was last verified' , '', 'date_current_ceo_was_last_verified', 'string' ),
('Web location of pro-forma 990s to handle Pharmaceutical valuation adjustments' , '', 'web_location_of_proforma_990s_to_handle_pharmaceutical_valuation_adjustments', 'string' ),
('Fiscal Year of Financial Rating' , '', 'fiscal_year_of_financial_rating', 'string' ),
('Fundraising Efficiency Amount' , '', 'fundraising_efficiency_amount', 'number' ),
('Fundraising Expense Ratio' , '', 'fundraising_expense_ratio', 'string' ),
('Program Expense Ratio' , '', 'program_expense_ratio', 'string' ),
('Administrative Expense Ratio' , '', 'administrative_expense_ratio', 'string' ),
('Working Capital Ratio' , '', 'working_capital_ratio', 'string' ),
('Fundraising Efficiency Score' , '', 'fundraising_efficiency_score', 'number' ),
('Fundraising Expense Score' , '', 'fundraising_expense_score', 'number' ),
('Program Expense Score' , '', 'program_expense_score', 'number' ),
('Administrative Expense Score' , '', 'administrative_expense_score', 'number' ),
('Primary Revenue Growth Score' , '', 'primary_revenue_growth_score', 'number' ),
('Program Expense Growth Score' , '', 'program_expense_growth_score', 'number' ),
('Working Capital Score' , '', 'working_capital_score', 'number' ),
('Score in the Financial dimension' , '', 'score_in_the_financial_dimension', 'number' ),
('Score in the A&T dimension' , '', 'score_in_the_a&t_dimension', 'number' ),
('Rating in the A&T dimension' , '', 'rating_in_the_a&t_dimension', 'number' ),
('Score in the Results dimension' , '', 'score_in_the_results_dimension', 'number' ),
('Rating in the Results Dimension' , '', 'rating_in_the_results_dimension', 'number' ),
('Overall Score' , '', 'overall_score', 'number' ),
('Overall Rating' , '', 'overall_rating', 'number' ),
('Yes/No indicator: This rating is a Donor Advisory' , '', 'yes_no_indicator_this_rating_is_a_donor_advisory', 'boolean' );
