INSERT INTO base_fields (label, short_code, data_type) VALUES
('Organization IRS Name', 'organization_irs_name', 'freeFormText' ),
('Organization IRS Address', 'organization_irs_address', 'freeFormText' ),
('Organization IRS City', 'organization_irs_city', 'freeFormText' ),
('Organization IRS State', 'organization_irs_state', 'freeFormText' ),
('Organization IRS Zip', 'organization_irs_zip', 'freeFormText' ),
('Organization IRS Subsection', 'organization_irs_subsection', 'freeFormText' ),
('Organization IRS Classification', 'organization_irs_classification', 'freeFormText' ),
('Organization IRS Foundation Information', 'organization_irs_foundation_information', 'freeFormText' ),
('Organization Tax Period', 'organization_tax_period', 'date' ),
('Organization Ruling Date', 'organization_ruling_date', 'date' ),
('Organization Demographic Info Required', 'organization_demographic_info_required', 'trueOrFalse' ),
('Organization Demographics Last Updated', 'organization_demographics_last_updated', 'date' ),
('Organization Audit Last Completed', 'organization_audit_last_completed', 'date' ),
('Organization Audit Auditor Name', 'organization_audit_auditor_name', 'freeFormText' ),
('Organization Audit Important Notes', 'organization_audit_important_notes', 'freeFormText');
