name: Add to project

on:
  issues:
    types: [opened, transferred, reopened]

jobs:
  add-to-project:
    uses: PhilanthropyDataCommons/.github/.github/workflows/add-to-project.yml@main
    secrets: inherit
