name: Drop and create preview DBs

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  CONNECTION_STRING: ${{ secrets.DEPLOY_PREVIEWS_PSQL_CONNECTION_STRING }}
  DATABASE_NAME: preview_${{ github.event.pull_request.number }}

concurrency:
  group: preview-db-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  create-db:
    runs-on: ubuntu-latest
    if: contains(fromJSON('["opened", "reopened", "synchronize"]'), github.event.action)
    container:
      image: alpine/psql:latest
      env:
        CONNECTION: ${{ env.CONNECTION_STRING }}
        DB_NAME: ${{ env.DATABASE_NAME }}
    steps:
      - name: Create a database for this PR on the "deploy previews" cluster
        run: |
          psql "${CONNECTION}" -c "DROP DATABASE IF EXISTS ${DB_NAME};"
          psql "${CONNECTION}" -c "CREATE DATABASE ${DB_NAME} TEMPLATE pdc;"

  drop-db:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    container:
      image: alpine/psql:latest
      env:
        CONNECTION: ${{ env.CONNECTION_STRING }}
        DB_NAME: ${{ env.DATABASE_NAME }}
    steps:
      - name: Drop a database for this PR on the "deploy previews" cluster
        run: |
          psql "${CONNECTION}" -c "DROP DATABASE IF EXISTS ${DB_NAME};"
