on:
  push:
    branches:
      - main
      - 137-wp-publishing
    paths:
      - 'docs/**/*.md'
  workflow_dispatch:
    inputs:
      force_publish:
        description: 'Force republish all posts'
        default: 'false'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Publish to WordPress
        uses: OpenTechStrategies/wp-post-gfm@main
        with:
          directory: 'docs'
          force_publish: true
          WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
          WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
          WORDPRESS_APP_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}