name: Test docker build

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: philanthropydatacommons/service

on:
  pull_request:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Build with node
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
      - run: npm ci
      - run: npm run build
      - run: npm prune --omit=dev
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build but do not push and do not write to cache
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
